version: '3.3'
services:
  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

