version: '3.3'
services:
  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

